### ISSUE TITLE
Not working with Angular 2 rc4

### ISSUE THREAD

**Issue by gaurav2887** [bharatraj88/angular2-tooltip#1]
I am importing in my existing Angular 2 component with these steps:
1. Added `import { ToolTipComponent } from 'angular2-tooltip/tool-tip.component';` to my component
2. Added ToolTipComponent  as directive
3. `span tooltip ngToolTipClass="tooltip" content="You can have any html or plain text content here"> </span>`

Getting error in tool-tip.component:

Module build failed: Error: Cannot resolve module 'angular2/core' in \node_modules\angular2-tooltip. I think angular2/core is changed to @angular/core. Also, This does not exist in rc4 `import { DOM } from 'angular2/src/platform/dom/dom_adapter';`

Also , Giving error in ComponentRef geneic type. Can you please help?

**Comment by bharatraj88** [comment]
Currently the component supports only beta version of angularjs2. I shall release the component with rc version of angular2 ASAP

**Comment by gaurav2887** [comment]
Thanks.Let me know when you release the rc version.
