### ISSUE TITLE
import module

### ISSUE THREAD

**Issue by Leggy7** [bharatraj88/angular2-tooltip#11]
There must be something trivial on this concern but I really can't have the ToolTipModule imported.

I'm doing:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { TooltipModule } from 'angular2-tooltip'; (<-- also tried 'ng2-tooltip' like the doc says)

[...]

@NgModule({
  declarations: [
    AppComponent,
    MznvComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    TooltipModule
  ],

[...]
```

I have the module resolution configured with "node" and I can't sort out why it is not recognizing the module. Also restarted the service (ng serve), no luck.

What could I be missing?

**Comment by SanjuSudheerM** [comment]
+1

**Comment by ericel** [comment]
I am not sure if it's the same module but they have the same name.
[https://github.com/pleerock/ng2-tooltip](https://github.com/pleerock/ng2-tooltip)

**Comment by joeyjreij** [comment]
import { ToolTipModule } from 'angular2-tooltip/src/tool-tip.module';

**Comment by bharatraj88** [comment]
Please upgrade to 3.0.0 version
Now you will be able to import from the root folder.
Example || import { ToolTipModule } from 'angular2-tooltip';

@joeyjreij  Thanks for updating in interim.

**Comment by bharatraj88** [comment]
@ericel  Nope! Its not same

**Comment by joeyjreij** [comment]
@bjaratraj88 update tooltip? Or angular? I've been tackeling this problem 3 months, but i assume that u ment updating the tooltip, so that's what i will try asap :)

Thanks

**Comment by bharatraj88** [comment]
update, please upgrade to 3.0.2

**Comment by bharatraj88** [comment]
Meant to upgrade tooltip :-)
