### ISSUE TITLE
Hello World Failure 

### ISSUE THREAD

**Issue by ghost** [bharatraj88/angular2-tooltip#14]
**There is no ng2-tooltip so this fails:**

import {TooltipModule} from 'ng2-tooltip'
 
@NgModule({
    imports: [
        ...
        TooltipModule   **The module is ToolTipModule (note case) so this fails**

I know, it's minor but this is the *only* documentation and it couldn't be simpler to at least get that tiny bit right.  it's more than just annoying because you then worry about the code itself -- is it just slapped together?

P.S. You had an opportunity to create a very sleek tooltip for browser and mobile; instead it's even more of an eye-sore than the standard tooltip.  Of course, we can put in our own HTML and CSS -- but why not have a sensible, reasonably attractive default?

**Comment by bharatraj88** [comment]
@Cogitaria  Thank you for your valuable suggestion. Have released on with default stylings in v3.1.0
