### ISSUE TITLE
Tooltip only when clicking a button?

### ISSUE THREAD

**Issue by agustincelentano** [bharatraj88/angular2-tooltip#2]
Is there possible to activate the tooltip when clicking a button? Like a Copied! message in a "Copy to Clipboard button"? 

I am trying to test it by adding it "import { ToolTipModule } from 'angular2-tooltip'; but it does not found the library. Am I referencing it well? Do you have any example?

**Comment by bharatraj88** [comment]
You can add the above as a feature request and I can make the corresponding changes.

Current tooltip supports angular2 2.1.1 version. You need to import this into your @NgModule. Please go through for example
https://github.com/bharatraj88/angular2-tooltip/blob/master/test/test.module.ts
