### ISSUE TITLE
Needs to be updated to angular 2.2.0

### ISSUE THREAD

**Issue by MMH919** [bharatraj88/angular2-tooltip#8]
Angular has been updated to 2.2.0.
The required version to run is currently 2.1.0

` +-- UNMET PEER DEPENDENCY @angular/common@2.2.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.2.0
+-- UNMET PEER DEPENDENCY @angular/core@2.2.0
+-- UNMET PEER DEPENDENCY @angular/http@2.2.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.2.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.2.0
-- angular2-tooltip@2.2.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angular2-tooltip@2.2.0 requires a peer of @angular/common@2.1.1 but none was installed.
npm WARN angular2-tooltip@2.2.0 requires a peer of @angular/http@2.1.1 but none was installed.
npm WARN angular2-tooltip@2.2.0 requires a peer of @angular/compiler@2.1.1 but none was installed.
npm WARN angular2-tooltip@2.2.0 requires a peer of @angular/core@2.1.1 but none was installed.
npm WARN angular2-tooltip@2.2.0 requires a peer of @angular/platform-browser@2.1.1 but none was installed.
npm WARN angular2-tooltip@2.2.0 requires a peer of @angular/platform-browser-dynamic@2.1.1 but none was installed.
npm WARN angulartest@1.0.0 No license field. `

**Comment by bharatraj88** [comment]
Issue fixed
Please upgrade to 2.2.1
